#!/bin/sh

set -e

case "$1" in
    configure)
        if [ "x"$2 != "x" ]; then
            # we are doing an upgrade
            exit 0
        fi
        cat /etc/shadow | awk -F ':' '{ print $1 }' | grep -E '^cuckoo$' || useradd -d /usr/share/cuckoo/ -r cuckoo
        chown -R cuckoo /var/log/cuckoo /var/lib/cuckoo
        systemctl daemon-reload
    ;;
    
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;
    
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
