#!/bin/sh

set -e

case "$1" in
    remove|purge)
        service cuckoo stop
        ;;
    upgrade)
        ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
